"""update height on user_profiles

Revision ID: 4a88e746f1f0
Revises: b62db01fd702
Create Date: 2026-08-17 18:25:47.125259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a88e746f1f0'
down_revision: Union[str, Sequence[str], None] = 'b62db01fd702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('height_cm', sa.Numeric(), nullable=True))
    op.drop_column('user_profiles', 'height_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('height_kg', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'height_cm')
    # ### end Alembic commands ###
