"""fix: update AI suggestion schema

Revision ID: 55b31bfb2043
Revises: fdd8c9e89868
Create Date: 2026-08-19 18:33:32.873895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b31bfb2043'
down_revision: Union[str, Sequence[str], None] = 'fdd8c9e89868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
