"""add height, age, sex to user_profiles

Revision ID: b62db01fd702
Revises: 9250bb50dae0
Create Date: 2026-08-17 17:40:09.440443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62db01fd702'
down_revision: Union[str, Sequence[str], None] = '9250bb50dae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('height_kg', sa.Numeric(), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.Numeric(), nullable=True))
    op.add_column('user_profiles', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'sex')
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'height_kg')
    # ### end Alembic commands ###
